version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2017
install:
- ps: ./gradlew clean -PjenkinsBuild --no-daemon
cache: C:\Users\appveyor\.gradle
build_script:
- ps: ./gradlew build -PjenkinsBuild --continue --no-daemon
test: off
artifacts:
- path: '**/libs/*'
  name: Jars
deploy:
- provider: GitHub
  auth_token:
    secure: jecQI2sLa3l2Ubgls0IS5xeqCezIqisLyC4y8VSm7JZzXM7r+wWc7Fs7aoCQJ51G
  artifact: /.*\.*/
  on:
    appveyor_repo_tag: true
